// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaWE-xLtEv0tg1yevLxM-aqGvuFRKOcu8',
    appId: '1:1035260998061:web:b7e4669c3c1c04850b7124',
    messagingSenderId: '1035260998061',
    projectId: 'event-form-fb9eb',
    authDomain: 'event-form-fb9eb.firebaseapp.com',
    storageBucket: 'event-form-fb9eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaCVigzwVRuDy6pU6lrfex6gyAY8Tg9BM',
    appId: '1:1035260998061:android:da0d4ae568a20d7a0b7124',
    messagingSenderId: '1035260998061',
    projectId: 'event-form-fb9eb',
    storageBucket: 'event-form-fb9eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGbgbLSrJQXv2Chgr60wRx_ooUZ3S_EJg',
    appId: '1:1035260998061:ios:f327909011fd04bc0b7124',
    messagingSenderId: '1035260998061',
    projectId: 'event-form-fb9eb',
    storageBucket: 'event-form-fb9eb.firebasestorage.app',
    iosBundleId: 'com.teste.formEventApp',
  );
}
